### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by dleshem** [adyenpayments/java#2]
Please add adyen-wsdl-cxf.jar to Maven.

**Comment by PatrickHuetter** [comment]
+1

**Comment by HugoTrimp** [comment]
Thanks for your suggestion. We had a look, but reckon our JAR doesn't belong to Maven. Perhaps the following would be an option for you: http://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html

**Comment by dleshem** [comment]
![image](https://cloud.githubusercontent.com/assets/1689757/6213104/0eb32974-b5f5-11e4-9c32-f81d9f85beee.png)
